from PIL import Image as im
import os
import csv


input_ = input("Enter the photos directory(Do not end with /): ")
input2 = input("Enter the Album Name: ")
print("Processing")

f = "P" + input_.replace("/","-")+".csv"

try:
	os.mkdir("thumbs/"+input_.split("/")[-1])
except FileExistsError:
	pass

output = "thumbs/"+input_.split("/")[-1]+"/"

height = 180
width = 270

with open(f, 'w') as writeFile:
	writer = csv.writer(writeFile)

	for x in os.listdir(input_):
		format = "PNG"
		if x.lower().endswith(".jpg") or x.lower().endswith(".jpeg"):
			format = "JPEG"
		img = im.open(input_+"/"+x)
		if img.size[1] < img.size[0]:
			p = (height/img.size[1])
			img = img.resize((int(float(img.size[0])*p),height),im.ANTIALIAS)
			img.save(output+x,format,quality=85)
		else:
			p = (width/img.size[0])
			img = img.resize((width,int(float(img.size[1])*p)),im.ANTIALIAS)
			img.save(output+x,format,quality=85)
		writer.writerow([input2,'images/'+input_.split("/")[-1]+"/"+x])
writeFile.close()

print("Now go to the cloud bucket\nGo to Media Folder, then to images, over there upload the main folder\nafter that go back, you will find thumbs folder, in that go to images and then upload the thumbs folder generated by the code in the folder code is residing\nNow go to https://interiit.com/forms/gallery_handler/ over there upload the generated csv.")